import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChatMessageHeader } from './ChatMessageHeader';
import { playerVariants, iconVariants } from '../../motion/audioAnimations';

interface AudioMessageProps {
  isSpeaking: boolean;
  onSpeech: () => void;
  modelName?: string;
  hasThought?: boolean;
  isThoughtExpanded?: boolean;
  onToggleThought?: () => void;
  isGenerating?: boolean;
  localFeedback?: 'like' | 'dislike' | null;
  handleFeedback?: (type: 'like' | 'dislike' | null) => void;
  isTemporary?: boolean;
}

export const AudioMessage: React.FC<AudioMessageProps> = ({
  isSpeaking,
  onSpeech,
  modelName,
  hasThought = false,
  isThoughtExpanded = false,
  onToggleThought = () => {},
  isGenerating = false,
  localFeedback,
  handleFeedback,
  isTemporary = false
}) => {
  const bars = Array.from({ length: 16 });

  return (
    <div className="flex flex-col w-full group/audio max-w-2xl">
      <ChatMessageHeader
        hasThought={hasThought}
        isExpanded={isThoughtExpanded}
        onToggleThought={onToggleThought}
        onSpeech={onSpeech}
        isSpeaking={isSpeaking}
        modelName={modelName}
        isGenerating={isGenerating}
      />

      <motion.div
        variants={playerVariants}
        initial="initial"
        animate="animate"
        exit="exit"
        className="mt-3 overflow-hidden rounded-[24px] bg-[#1e1e1e] border border-[#3c4043] hover:border-[#5f6368] transition-colors shadow-sm"
      >
        <div className="flex items-center gap-4 px-4 py-3">
          {/* Play/Pause Button - MD3 FAB style */}
          <button
            onClick={onSpeech}
            className={`w-12 h-12 flex items-center justify-center rounded-full transition-all active:scale-90 relative overflow-hidden ${
              isSpeaking 
              ? 'bg-[#8ab4f8] text-[#000]' 
              : 'bg-[#3c4043] text-[#8ab4f8] hover:bg-[#4a4d51]'
            }`}
          >
            <AnimatePresence mode="wait" initial={false}>
              <motion.span
                key={isSpeaking ? 'pause' : 'play'}
                variants={iconVariants}
                initial="initial"
                animate="animate"
                exit="exit"
                className="material-symbols-outlined text-[28px] absolute"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                {isSpeaking ? 'pause' : 'play_arrow'}
              </motion.span>
            </AnimatePresence>
          </button>

          <div className="flex flex-col flex-1 min-w-0">
            <div className="flex items-center gap-2">
              <span className={`text-sm font-semibold tracking-wide transition-colors ${isSpeaking ? 'text-[#8ab4f8]' : 'text-[#e2e2e2]'}`}>
                {isSpeaking ? 'Playing Audio...' : 'Voice Response'}
              </span>
              {isGenerating && (
                <div className="w-2 h-2 rounded-full bg-[#8ab4f8] animate-pulse" />
              )}
            </div>
            
            <div className="flex items-center gap-3 h-6 mt-0.5">
              {isSpeaking ? (
                <div className="flex items-end gap-[3px] h-4">
                  {bars.map((_, i) => (
                    <motion.div
                      key={i}
                      animate={{ 
                        height: [4, 16, 8, 14, 6, 12, 4],
                      }}
                      transition={{
                        repeat: Infinity,
                        duration: 1 + Math.random() * 0.5,
                        ease: "easeInOut",
                        delay: i * 0.05
                      }}
                      className="w-[2px] bg-[#8ab4f8] rounded-full"
                    />
                  ))}
                </div>
              ) : (
                <span className="text-xs text-[#808080] font-medium truncate">
                  Generated by {modelName || 'Gemini Flash 3.1 TTS'}
                </span>
              )}
            </div>
          </div>

          <div className="flex-shrink-0 flex items-center gap-1">
            <div className={`p-2 rounded-full ${isSpeaking ? 'text-[#8ab4f8]' : 'text-[#5f6368]'}`}>
              <span className="material-symbols-outlined text-[20px]" style={{ fontVariationSettings: isSpeaking ? "'FILL' 1" : "" }}>
                {isSpeaking ? 'equalizer' : 'graphic_eq'}
              </span>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Modern MD3 Feedback */}
      {!isGenerating && !isTemporary && handleFeedback && (
        <div className="mt-3 flex items-center gap-2 px-1">
          <button
            onClick={() => handleFeedback(localFeedback === 'like' ? null : 'like')}
            className={`flex items-center gap-2 px-4 py-1.5 rounded-full border transition-all ${
              localFeedback === 'like' 
              ? 'bg-[#8ab4f8]/10 border-[#8ab4f8] text-[#8ab4f8]' 
              : 'bg-transparent border-[#3c4043] text-[#808080] hover:bg-[#282a2d] hover:border-[#5f6368]'
            }`}
          >
            <span
              className="material-symbols-outlined text-[18px]"
              style={{ fontVariationSettings: localFeedback === 'like' ? "'FILL' 1" : "" }}
            >
              thumb_up
            </span>
            <span className="text-xs font-semibold">Good</span>
          </button>
          
          <button
            onClick={() => handleFeedback(localFeedback === 'dislike' ? null : 'dislike')}
            className={`flex items-center justify-center w-10 h-10 rounded-full border transition-all ${
              localFeedback === 'dislike' 
              ? 'bg-[#f28b82]/10 border-[#f28b82] text-[#f28b82]' 
              : 'bg-transparent border-[#3c4043] text-[#808080] hover:bg-[#282a2d] hover:border-[#5f6368]'
            }`}
          >
            <span
              className="material-symbols-outlined text-[18px]"
              style={{ fontVariationSettings: localFeedback === 'dislike' ? "'FILL' 1" : "" }}
            >
              thumb_down
            </span>
          </button>
        </div>
      )}
    </div>
  );
};


